version: "3"
services:

  client:
    build: 
      context: front-end
      dockerfile: Dockerfile
    ports:
      - 7002:7002
    networks:
      - mern-network
    volumes:
      - front-end/src
      - front-end/public
    depends_on:
      - server
    environment:
      - REACT_APP_SERVER=http://localhost:5002
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    stdin_open: true
    tty: true
  
  server:
    build:
      context: back-end
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    networks:
      - mern-network
    volumes:
      - back-end
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017
      - CLIENT=http://localhost:7002
    command: /usr/app/node_modules/.bin/nodemon -L src/index.js

  db:
    image: mongo:3.6.19-xenial
    ports:
      - 27017:27017
    networks:
      - mern-network
    volumes:
      - back-end/database

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local